# database init, supports postgres too
database=postgres
spring.datasource.url=${POSTGRES_URL:jdbc:postgresql://localhost/petclinic}
spring.datasource.username=${POSTGRES_USER:petclinic}
spring.datasource.password=${POSTGRES_PASS:petclinic}
spring.docker.compose.readiness.timeout=5m
spring.docker.compose.readiness.tcp.connect-timeout=5s
spring.docker.compose.readiness.tcp.read-timeout=5s
# SQL is written to be idempotent so this is safe
spring.sql.init.mode=always
